import React, { useContext, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FacultyUserAuthContextType } from "@/types/FacultyUserAuthContextTypes";
import { FacultyUserAuthContext } from "@/hooks/contexts/FacultyUserAuthContextProvider";
import { useRouter } from "next/router";
import {
  SchoolContext,
  SchoolProvider,
} from "@/hooks/contexts/SchoolContextProvider";
import { SchoolContextType } from "@/types/SchoolContextTypes";
import { SchoolInfoCard } from "@/components/SchoolnfoCard";
import { CreateCalendarEventForm } from "@/modules/CreateCalendarEventForm";
import { EventsProvider } from "@/hooks/contexts/EventsContextProvider";
import { EventsInfoCard } from "@/components/EventsInfoCard";

export default function Home() {
  let router = useRouter();
  const { facultyUser, isAuthenticated } = useContext(
    FacultyUserAuthContext
  ) as FacultyUserAuthContextType;
  //const { school } = useContext(SchoolContext) as SchoolContextType;
  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/signup");
    }
    // if (!school) {
    //   router.push("school_registration");
    // }
  }, [isAuthenticated, router]); // add school back into list
  return (
    <>
      <Head>
        <title>Home | EduConnect </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="mx-80">
          <div className="">
            <h1 className="text-3xl font-bold text-custom_primary">
              Welcome {facultyUser?.accountHolderFullName.firstName}
            </h1>

            <button
              onClick={() => router.push("/school_registration")}
              className="mt-4 mr-4 inline-block rounded border border-custom_secondary-500 font-medium px-12 py-4 text-white bg-custom_secondary-500"
            >
              Register School
            </button>

            <button
              onClick={() => router.push("/calendar")}
              className="mt-4 inline-block rounded border border-custom_secondary-500 font-medium px-12 py-4 text-white bg-custom_secondary-500"
            >
              Calendar
            </button>

            <button
              onClick={() => router.push("/parent_messages")}
              className="ml-4 mt-4 inline-block rounded border border-custom_secondary-500 font-medium px-12 py-4 text-white bg-custom_secondary-500"
            >
              Parent Messages
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
