import React, { useState, useContext, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { axiosClient } from "@/axiosClient";
import {
  getFacultyUserJWTToken,
  storeFacultyUserJWTToken,
} from "../../utils/localStorage";
import { FacultyUserAuthContext } from "@/hooks/contexts/FacultyUserAuthContextProvider";
import { FacultyUserAuthContextType } from "@/types/FacultyUserAuthContextTypes";
import { useRouter } from "next/router";

export default function Login() {
  let router = useRouter();
  const { isAuthenticated, facultyUserAuthLogin } = useContext(
    FacultyUserAuthContext
  ) as FacultyUserAuthContextType;
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");

  useEffect(() => {
    if (isAuthenticated) {
      router.push("/");
    }
  }, [isAuthenticated, router]);

  const handleSubmit = async (): Promise<void> => {
    axiosClient
      .post("v1/faculty/facultyUserLogin", {
        email: email,
        password: password,
      })
      .then((res) => {
        const { accountHolderFullName, email, jwtToken, user_id } = res.data;
        storeFacultyUserJWTToken(jwtToken);
        facultyUserAuthLogin({
          accountHolderFullName: {
            firstName: accountHolderFullName.firstName,
            lastName: accountHolderFullName.lastName,
          },
          email: email,
          user_id: user_id,
        });
        axiosClient.defaults.headers.common.Authorization = `Bearer ${jwtToken}`;
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Faculty Login | EduConnect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="mx-80">
          <div className="">
            <h1 className="text-3xl font-bold text-custom_primary">
              Faculty login
            </h1>

            <input
              type="text"
              id="email"
              placeholder="Email"
              className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4"
              onChange={(e) => setEmail(e.target.value)}
            />
            <input
              type="text"
              id="password"
              placeholder="password"
              className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4 "
              onChange={(e) => setPassword(e.target.value)}
            />

            <button
              onClick={handleSubmit}
              className="mt-4 inline-block rounded border border-custom_secondary-500 font-medium px-12 py-4 text-white bg-custom_secondary-500"
            >
              Login
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
