import React, { useContext, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FacultyUserAuthContextType } from "@/types/FacultyUserAuthContextTypes";
import { FacultyUserAuthContext } from "@/hooks/contexts/FacultyUserAuthContextProvider";
import { useRouter } from "next/router";
import { ParentMessagesProvider } from "@/hooks/contexts/ParentMessagesContextProvider";
import { ParentMessagesCard } from "@/components/ParentMessagesCard";

export default function Home() {
  let router = useRouter();
  const { isAuthenticated } = useContext(
    FacultyUserAuthContext
  ) as FacultyUserAuthContextType;

  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/signup");
    }
  }, [isAuthenticated, router]);

  return (
    <>
      <Head>
        <title>Parent Messages | EduConnect </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="mx-80">
          <div className="">
            <h1 className="text-3xl font-bold text-custom_primary">
              Parent Messages
            </h1>
            <ParentMessagesProvider>
              <ParentMessagesCard />
            </ParentMessagesProvider>
          </div>
        </div>
      </main>
    </>
  );
}
