import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useContext, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { axiosClient } from "@/axiosClient";
import { FacultyUserAuthContext } from "@/hooks/contexts/FacultyUserAuthContextProvider";
import { FacultyUserAuthContextType } from "@/types/FacultyUserAuthContextTypes";
import { SchoolContextType } from "@/types/SchoolContextTypes";
import { SchoolContext } from "@/hooks/contexts/SchoolContextProvider";

export default function RegisterSchool() {
  let router = useRouter();
  const { isAuthenticated, facultyUser } = useContext(
    FacultyUserAuthContext
  ) as FacultyUserAuthContextType;
  const { school, addSchoolInfo } = useContext(
    SchoolContext
  ) as SchoolContextType;
  const [schoolName, setSchoolName] = useState<String>("");
  const [street, setStreet] = useState<String>("");
  const [city, setCity] = useState<String>("");
  const [state, setState] = useState<String>("");
  const [zip, setZip] = useState<String>("");
  const [country, setCountry] = useState<String>("");

  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/signup");
    }
    if (school) {
      router.push("/");
    }
  }, [isAuthenticated, school, router]);

  const handleSubmit = async (): Promise<void> => {
    await axiosClient
      .post("/v1/faculty/schoolRegistration", {
        name: schoolName,
        address: {
          street: street,
          city: city,
          state: state,
          zip: zip,
          country: country,
        },
        facultyUser: facultyUser?.user_id,
      })
      .then((res) => {
        addSchoolInfo(res.data);
        router.push("/");
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Register school | EduConnect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="mx-80">
          <div className="">
            <h1 className="text-3xl font-bold text-custom_primary">
              Register School
            </h1>
            <input
              type="text"
              id="schoolName"
              placeholder="School name"
              className="w-full rounded-md border-custom_secondary-500 border-2  shadow-sm mt-4"
              onChange={(e) => setSchoolName(e.target.value)}
            />
            <div className="flex items-center">
              <input
                type="text"
                id="streetAddress"
                placeholder="Street address"
                className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4"
                onChange={(e) => setStreet(e.target.value)}
              />
              <input
                type="text"
                id="cityName"
                placeholder="City name"
                className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4 ml-4"
                onChange={(e) => setCity(e.target.value)}
              />
            </div>
            <div className="">
              <input
                type="text"
                id="state"
                placeholder="State name"
                className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4"
                onChange={(e) => setState(e.target.value)}
              />
              <input
                type="text"
                id="zipCode"
                placeholder="Zip code"
                className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4"
                onChange={(e) => setZip(e.target.value)}
              />
              <input
                type="text"
                id="countryName"
                placeholder="Country name"
                className="w-full rounded-md border-custom_secondary-500 border-2 shadow-sm mt-4"
                onChange={(e) => setCountry(e.target.value)}
              />
            </div>
            <button
              onClick={handleSubmit}
              className="mt-4 inline-block rounded border border-custom_secondary-500 font-medium px-12 py-4 text-white bg-custom_secondary-500"
            >
              Register School
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
